spring.application.name=agendador-tarefas
spring.data.mongodb.uri=mongodb://localhost:27017/db_agendador
usuario.url=localhost:8081
server.port=8082
usuario.email=michaeljackson@gmail.com
usuario.senha=12345Michael
spring.jackson.serialization.write-dates-as-timestamps=true
jwt.secret=Zm9vYmFyYmF6cXV4cXV1eG9yZ3JhaWxzaXRhbG8yMDI2Zml0ZWM=