spring.application.name=agendador-tarefas
usuario.url=localhost:8081
server.port=8082
usuario.email=michaeljackson@gmail.com
usuario.senha=12345Michael
spring.jackson.serialization.write-dates-as-timestamps=true
jwt.secret=Zm9vYmFyYmF6cXV4cXV1eG9yZ3JhaWxzaXRhbG8yMDI2Zml0ZWM=

spring.datasource.url=jdbc:postgresql://localhost:5432/agendador
spring.datasource.username=agendador
spring.datasource.password=admin

spring.jpa.hibernate.ddl-auto=update